### ISSUE TITLE
some question on advloss

### ISSUE THREAD

**Issue by PAIYUTSUTW** [leafinity/keras_ganomaly#2]
hi, i have some question on advloss

in your code, you use K.mean to calculating the average value of gan feature before it subtract from ori feature.
like this
"K.mean(K.square(ori_feature - K.mean(gan_feature, axis=0)))"

Is it necessary for calculating the average value of gan feature?
Can i subtract gan feature from ori feature without doing it?
like this
"K.mean(K.square(ori_feature - gan_feature))"

thanks

**Comment by forechoandlook** [comment]
![image](https://user-images.githubusercontent.com/50866639/120071627-c9fe3280-c0c2-11eb-928c-441a69983c16.png)
As the image from paper describes , the total loss contains the loss.
![image](https://user-images.githubusercontent.com/50866639/120071696-09c51a00-c0c3-11eb-87ba-d611b56bdb93.png)
Maybe you need read paper firstly. Here is the link : https://arxiv.org/pdf/1805.06725.pdf
